config/routes.rb
Rails.application.routes.draw do
  get 'surveys/index'

  get 'surveys/new'

  root 'users#home'
  get '/login' => 'sessions#new'
  get 'signup' => 'users#new'
  get 'manage_account' => 'users#index'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  resources :responses
#get '/questions' =>  'questions#index'
#get '/new_questions' => 'questions#new'
#post 'questions' => 'questions#create'
  get 'surveys/_form'=> 'survey#new'
  resources :users
  resources :questions do
    collection do
      delete 'destroy_multiple' 
    end
  end
  resources :surveys do
    collection do
      delete 'destroy_multiple' 
    end
    member do
      get 'respond'
      post 'submitResponse' => 'surveys#submitResponse'
    end
  end
end

app/models/question.rb
class Question < ActiveRecord::Base
	has_many :question_surveys
	has_many :surveys, through: :question_surveys
	before_create :generate_token
 	protected
=begin
 	Use hashing instead later.
 	This does not generate a unique value
=end
 	def generate_token
		self.num=rand(999999)
    end
end

app/controllers/questions_controller.rb
class QuestionsController < ApplicationController
	def index
		@questions=Question.all
	end

	def new
		@question=Question.new
	end

	def create
		@question = Question.new(question_params)
    	if @question.save
    		flash[:success]="Question created"
     		redirect_to '/questions'
    	else
    		flash.now[:error]="please try again"
     		render '/'
    	end
	end

def edit
   @question = Question.find(params[:id])
end

def update
  @question = Question.find(params[:id])
  if @question.update(question_params)
    redirect_to '/questions'
  else
    render '/'
  end
end

def destroy_multiple

  Question.destroy(params[:questions])

  respond_to do |format|
    format.html { redirect_to '/questions' }
    format.json { head :no_content }
  end

end

	private 
	def question_params
    params.require(:question).permit(:id, :num, :context, :category)
    end

end

app/helpers/questions_helper.rb
module QuestionsHelper
end

app/views/questions/_form.html.erb
 <%= form_for (@question), :html => {:class => "form-horizontal center"} do |f| %>
 <br/>
     <%= f.select :category, options_for_select([ "Game", "Normal Workout" ]), {prompt: "Select Category"}, {class: "form-control"} %><br/>
      <!--<%= f.text_field :category, :placeholder => "Category" %> -->
     <%= f.text_area :context, :placeholder => "Question Content", class: "form-control" %>
     <br/>
     <%= f.submit "Create", class: "btn btn-primary" %>
 <% end %>

app/views/questions/edit.html.erb
<%= form_for (@question), :html => {:class => "form-horizontal center"} do |f| %>
<br />
<%=f.text_field :id, :placeholder => :id, :disabled => true, class: "form-control", type: "text"%> <br />

<%= f.select :category, options_for_select([ "Game", "Normal Workout" ]), {prompt: "Select Category"}, {class: "form-control"} %><br />

<%= f.text_area :context, :placeholder => :context, class: "form-control" %>

<br /><br />
<%= f.submit "Save Changes", class: "btn btn-primary" %>
<%end%>

app/views/questions/index.html.erb
<h4>Questions</h4>
<div class="new_q">
  <%= button_to "New Question", new_question_path, :class => "btn btn-primary btn-lg", :method => :get  %>
</div>
<div>
  <table class="table">
    <thead>
      <tr>
      <th></th>
      <th colspan="1">Question ID</th>
      <th colspan="1">Question Type</th>
      <th colspan="1">Content</th>
      <th colspan="1">Edit</th>
      <th colspan="1">Delete</th>
    </tr>
  </thead>
  <tbody>
<%= form_tag destroy_multiple_questions_path, method: :delete do %>
      <% @questions.each do |question| %> 
      <tr>
          <td> <%= check_box_tag "questions[]", question.id, false, class: "checkbox" %></td>
          <td><%= question.id %></td>
          <td><%= question.category%></td>
          <td><%= question.context%></td>
          <td><%= link_to "Edit", edit_question_path(question), {:class => "btn btn-primary"}%></td>
          <td><%= submit_tag "Delete selected", name: nil, class: "btn btn-danger btn-sm" %></td>
        </tr>
      <% end %>
      <br>
      <br>
        </div>
<% end %>
</tbody>
</table>
</div>

app/views/questions/new.html.erb
<%= render 'form' %>