config/routes.rb
Rails.application.routes.draw do
  get 'surveys/index'

  get 'surveys/new'

  root 'users#home'
  get '/login' => 'sessions#new'
  get 'signup' => 'users#new'
  get 'manage_account' => 'users#index'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  resources :responses
#get '/questions' =>  'questions#index'
#get '/new_questions' => 'questions#new'
#post 'questions' => 'questions#create'
  get 'surveys/_form'=> 'survey#new'
  resources :users
  resources :questions do
    collection do
      delete 'destroy_multiple' 
    end
  end
  resources :surveys do
    collection do
      delete 'destroy_multiple' 
    end
    member do
      get 'respond'
      post 'submitResponse' => 'surveys#submitResponse'
    end
  end
end

app/views/shared/_navigation.html.erb
<nav class="navbar navbar-default navbar-fixed-top" role="navigation">
  <div class="container">
    <div class="navbar-header">
      <button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#bs-example-navbar-collapse-1" aria-expanded="false">
        <span class="sr-only">Toggle navigation</span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
        <span class="icon-bar"></span>
      </button>
      <a class="navbar-brand" id="home" href="/">
        Home
      </a>
        
    </div>

    <div class="collapse navbar-collapse" id="bs-example-navbar-collapse-1">
     
      <ul class="nav navbar-nav" id = "menu">
        <% if current_user %> 

        <%if current_user.role === 'admin'%>
          <li class="active"><%= link_to "Manage Accounts" , manage_account_path %></li><span class="sr-only">(current)</span></li>
        <% end %>

        <li><a href="#">Calendar</a></li>

         <% if current_user.role === 'coach' %>
        <li> <%= link_to "Questions", questions_path %> </li>
        <% end %>
        
        <li class="dropdown">
          <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-haspopup="true" aria-expanded="false">Feedbacks<span class="caret"></span></a>
          <ul class="dropdown-menu">
            <li><%= link_to 'All Surveys', surveys_path %></li>
            
            <% if current_user.role === 'admin' || current_user.role === 'coach' %>
            <li><%= link_to 'Create Survey', new_survey_path %></li>
            <% end %>
            
            <li role="separator" class="divider"></li>            
            <li><%= link_to 'View Responses', responses_path %></li>

            <% if current_user.role === 'swimmer' %>
            <li><a href="#">Fill Out</a></li>
            <% end %>
          
          </ul>
        </li>
      
      </ul>
        <ul class="nav navbar-nav navbar-right" id="logout">
          <li><%= link_to "Log out", logout_path, :method => :delete %></li>
        </ul>

        <% else %>
        <ul class="nav navbar-nav"> 
          <li><%= link_to "Login", 'login' %></li>
          <li><%= link_to "Signup", 'signup' %></li>
        </ul>
      <%end%>
    </div>
</nav>