config/routes.rb
Rails.application.routes.draw do
  get 'surveys/index'

  get 'surveys/new'

  root 'users#home'
  get '/login' => 'sessions#new'
  get 'signup' => 'users#new'
  get 'manage_account' => 'users#index'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  resources :responses
#get '/questions' =>  'questions#index'
#get '/new_questions' => 'questions#new'
#post 'questions' => 'questions#create'
  get 'surveys/_form'=> 'survey#new'
  resources :users
  resources :questions do
    collection do
      delete 'destroy_multiple' 
    end
  end
  resources :surveys do
    collection do
      delete 'destroy_multiple' 
    end
    member do
      get 'respond'
      post 'submitResponse' => 'surveys#submitResponse'
    end
  end
end

app/controllers/responses_controller.rb
class ResponsesController < ApplicationController

	def index
		@user = current_user
		@surveys = []
		if @user.role != 'admin'
			@responses = Response.where(:user_id => @user.id)
		else
			@responses = Response.all
		end
		@responses.each do |r|
				@surveys << Survey.find_by(:id => r.survey_id)
		end
		@surveys = @surveys.uniq
	end

	def edit
		@survey = Survey.find_by(id: params[:id])
		@responses = Response.where(survey_id: params[:id], user_id: current_user.id)
	end

	def show
    	@survey = Survey.find_by(id: params[:id])
    	if current_user.role != 'admin'
    		@responses = Response.where(survey_id: params[:id], user_id: current_user.id)
    	else
    		@responses = Response.where(survey_id: params[:id])
    		#showByUser
    	end
    	@questions = Question.all
  	end

  	def showResponse
  		@survey = Survey.find_by(id: params[:id])
    	if current_user.role != 'admin'
    		@responses = Response.where(survey_id: params[:id], user_id: current_user.id)
    	else
    		@responses = Response.where(survey_id: params[:id])
    		#showByUser
    	end
    	@questions = Question.all

  	end

end

app/helpers/responses_helper.rb
module ResponsesHelper
end

app/views/responses/_form.html.erb
<%= form_for (@survey), :html => {:class => "form-horizontal center"} do |f| %>
<br />
<label for="surveyTitle">Survey Title</label>
<%=f.text_field :title, class: "form-control", type: "text" , :readonly => true %> <br />
<label for="surveyDate">Date</label>
<%=f.text_field :date, class: "form-control", type: "date", :readonly => true %><br />

<label for="userID">User ID: <%= current_user.id %></label> <br><br>

<label for="category">Category</label> <br />
<%= f.select :category, options_for_select([ "Swim Match", "Normal Workout" ]), {:onchange => "reset_form(this.id,'page_type_msg');"},class: "form-control" , :readonly => true  %><br />

<label for="qANDa">Questions</label> <br />
<%= f.fields_for :responses, @responses do |r| %>
	<%= r.text_field :question, class: "form-control", type: "text", :readonly => true %> <br>
	<%= r.text_field :content, class: "form-control", type: "text" %>
<br />
<% end %>

<%= f.submit "Submit", class: "btn btn-primary" %>
<% end %>

app/views/responses/edit.html.erb
<%= render 'form' %>

app/views/responses/index.html.erb
<h4>Responses</h4>
<div>
  <table class="table">
    <thead>
      <tr>
      <th></th>
      <th colspan="1">Survey ID</th>
      <th colspan="1">User</th>
      <th colspan="1">Survey</th>
      <th colspan= "1">Date </th>
      <th colspan="1">Question</th>
      <th colspan="1">Content</th>
    </tr>
  </thead>
   <tbody>
 <%= @surveys.each do |s| %> 
  <tr>
      <td> <%= check_box_tag "responses[]", s.id, false, class: "checkbox" %></td>
      <td><%= s.id %></td> 
      <td><%= s.title %></td>
      <td><%= link_to("View", response_path(s), {:class => "btn btn-primary"}) %> </td>
      
  </tr>
<% end %>
</tbody>
</table>
</div>

app/views/responses/show.html.erb
<h4>Responses</h4>
<div>
  <table class="table">
    <thead>
      <tr>
      <th></th>
      <th colspan="1">Survey ID</th>
      <th colspan="1">User</th>
      <th colspan="1">Survey</th>
      <th colspan= "1">Date </th>
      <th colspan="1">Question</th>
      <th colspan="1">Content</th>
    </tr>
  </thead>
   <tbody>
 <%= @surveys.each do |s| %> 
  <tr>
      <td> <%= check_box_tag "responses[]", s.id, false, class: "checkbox" %></td>
      <td><%= s.id %></td> 
      <td><%= s.title %></td>
      <td><%= link_to("View", response_path(s), {:class => "btn btn-primary"}) %> </td>
      
  </tr>
<% end %>
</tbody>
</table>
</div>