config/routes.rb
Rails.application.routes.draw do
  get 'surveys/index'

  get 'surveys/new'

  root 'users#home'
  get '/login' => 'sessions#new'
  get 'signup' => 'users#new'
  get 'manage_account' => 'users#index'
  post 'login' => 'sessions#create'
  delete 'logout' => 'sessions#destroy'

  resources :responses
#get '/questions' =>  'questions#index'
#get '/new_questions' => 'questions#new'
#post 'questions' => 'questions#create'
  get 'surveys/_form'=> 'survey#new'
  resources :users
  resources :questions do
    collection do
      delete 'destroy_multiple' 
    end
  end
  resources :surveys do
    collection do
      delete 'destroy_multiple' 
    end
    member do
      get 'respond'
      post 'submitResponse' => 'surveys#submitResponse'
    end
  end
end

app/models/survey.rb
class Survey < ActiveRecord::Base
	#has_many :questions, :dependent => :destroy
	has_many :questions, through: :question_surveys 
	has_many :question_surveys
	has_many :responses
	accepts_nested_attributes_for :questions, :question_surveys, :responses, allow_destroy: true
	#accepts_nested_attributes_for :questions,
end

app/controllers/surveys_controller.rb
class SurveysController < ApplicationController
  before_action :setSurvey, only: [:submitResponse, :respond, :show, :update, :edit]
  
  def index
  	@surveys=Survey.all
  end

  def new
  	@survey=Survey.new
    @questions=Question.all
  end

  def edit
    @survey_questions=QuestionSurvey.where(:survey => @survey)
    @surveyquestions=[]
    @survey_questions.each do |sq|
      @surveyquestions << sq.question_id
    end
    @questions=Question.all
  end

  def create
  	@survey=Survey.new(survey_params)
    @questionson=params[:question][:question_id]
    for q in @questionson
      @survey.question_surveys.build(:question_id => q, :survey_id => @survey.id) 
    end
    #@survey.question_surveys.build(:question_id => (params[:question][:question_id]), :survey_id => @survey.id) 
  	if @survey.save
  		flash[:success]="Survey Created"
  		redirect_to '/surveys'
  	else
  		flash.now[:error]="Please try again"
  		render'/'
  	end
  end


  def update
    @questionson=params[:question][:question_id]
    QuestionSurvey.where(:survey => @survey).destroy_all
    for q in @questionson
      @survey.question_surveys.build(:question_id => q, :survey_id => @survey.id) 
    end
    if @survey.update(survey_params)
      flash[:notice]="Survey Created"
      redirect_to '/surveys'
    else
      flash.now[:error]="Please try again"
      render'/'
    end
  end

  def show
    @survey_questions=QuestionSurvey.where(:survey => @survey)
    @surveyquestions=[]
    @survey_questions.each do |sq|
      @surveyquestions << sq.question_id
    end
    @questions=Question.all
  end

  def respond
    @response=Response.new
    @survey_questions=QuestionSurvey.where(:survey => @survey)
    @surveyquestions=[]
    @response=params[:response]
    @survey_questions.each do |sq|
      @surveyquestions << sq.question_id
    end
    @questions=Question.all
    
  end

def submitResponse
    @responses=params[:response][:responses]
    @questions=params[:response][:question_id]  
    for i in 0...@responses.size
      @response=Response.new
      @response.question_id = @questions[i]
      @response.question = Question.find_by(:id => @questions[i]).context
      @response.survey_id=@survey.id
      @response.content=@responses[i]
      @response.user_id = current_user.id
      @response.save
    end
    if @response.save
      flash[:success]="Responses Created"
      redirect_to '/surveys'
    else
      flash.now[:error]="Please try again"
      render'/'
    end
end

  def destroy_multiple

  Survey.destroy(params[:surveys])

  respond_to do |format|
    format.html { redirect_to '/surveys' }
    format.json { head :no_content }
  end
  end


  private

  def setSurvey
     @survey=Survey.find(params[:id]) 
  end

  def survey_params
  	params.require(:survey).permit(:id, :title, :date, :category, :question_id, questions_attributes: [:id, :context], question_surveys_attributes: [:survey_id, :question_id])
  end

  def response_params
    params.require(:survey).permit(:id, :title, :date, :category, :response [], :question_id, questions_attributes: [:id, :context], question_surveys_attributes: [:survey_id, :question_id], responses_attributes: [:survey_id, :question_id, :content])
  end
end

app/helpers/surveys_helper.rb
module SurveysHelper
end

app/views/surveys/_form.html.erb
<%= form_for (@survey), :html => {:class => "form-horizontal center"} do |f| %>
<br />
<%=f.text_field :title, :placeholder => "Title", class: "form-control", type: "text"%> <br />
<%=f.text_field :date, :placeholder => "Date", class: "form-control", type: "date"%><br />
<%= f.select :category, options_for_select([ "Swim Match", "Normal Workout" ]), {:onchange => "reset_form(this.id,'page_type_msg');"},class: "form-control"  %><br />

<%= collection_select(:question, :question_id, @questions, :id, :context, {:include_hidden =>false}, {:multiple => true}) %>
<br /><br />
<%= f.submit "Submit", class: "btn btn-primary" %>
<%end%>

app/views/surveys/edit.html.erb
<%= form_for (@survey), :html => {:class => "form-horizontal center"} do |f| %>
<br />
<%=f.text_field :title, class: "form-control", type: "text"%> <br />
<%=f.text_field :date, class: "form-control", type: "date"%><br />

<%= f.select :category, options_for_select([ "Swim Match", "Normal Workout" ]), {:onchange => "reset_form(this.id,'page_type_msg');"},class: "form-control"  %><br />

<%= collection_select(:question, :question_id, @questions, :id, :context, {:include_hidden =>false}, {:multiple => true}) %>
<br /><br />
<%= f.submit "Save Changes", class: "btn btn-primary" %>
<%end%>

app/views/surveys/form.html.erb
<%= fields_for :questions do |builder| %>

<!-- should be in form.html but just to show. Please delete later -->
	<fieldset>
		<%= builder.label :context, "Question" %> <br />
		<%= builder.text_area :context %> <br />
		<%= builder.check_box :_destroy %>
		<%= builder.label :_destroy, "Remove Question" %>
	</fieldset>
<% end %>

app/views/surveys/index.html.erb
<h4>Surveys</h4>
<!-- should be in form.html but just to show. Please delete later -->
<div>
   <%= button_to "New Survey", new_survey_path, :class => "btn btn-primary btn-lg", :method => :get  %>
  <table class="table">
    <thead>
      <tr>
      <th></th>
      <th colspan="1">ID</th>
      <th colspan="1">Title</th>
      <th colspan="1">Date</th>
      <th colspan="1">View</th>
      <th colspan="1">Respond</th>
      <th colspan="1">Delete</th>
    </tr>
  </thead>
   <tbody>
<%= form_tag destroy_multiple_surveys_path, method: :delete do %>
 <% @surveys.each do |survey| %> 
  <tr>
      <td> <%= check_box_tag "surveys[]", survey.id, false, class: "checkbox" %></td>
      <td><%= survey.id %></td>    
      <td><%= survey.title %></td>
      <td><%= survey.date %></td>
      <td><%= link_to("View", survey_path(survey), {:class => "btn btn-primary"}) %> </td>
      <td><%= link_to "Respond", respond_survey_path(survey), {:class => "btn btn-primary"}%></td>
      <td><%= submit_tag "Delete", name: nil, class: "btn btn-danger" %></td>
  </tr>
<% end %>
<br>
<br>
<% end %>
</tbody>
</table>
</div>

app/views/surveys/new.html.erb
<%= render 'form' %>

app/views/surveys/respond.html.erb
<%= form_for :response, :url => url_for(:id =>@survey.id, :action => "submitResponse"), :html => {:class => "form-horizontal center"} do |f| %>

<div class="survey">
<%=f.label @survey.title, class: "form-control" %>
<%=f.label @survey.date, class: "form-control" %>
<%= @surveyquestions.each do |sq| %>
	<%= f.label @questions.find(sq).context, class: "form-control" %>
	<%= f.hidden_field :question_id, :value => sq, multiple: true %>
	<%= f.text_area :responses, multiple: true, class: "form-control" %>
<% end %>
<%= f.submit "Submit", class: "btn btn-primary" %>
</div>
<% end %>

app/views/surveys/show.html.erb
<div class="survey">
      <h2><%= @survey.title %></h2>
      <h2><%= @survey.date %></h2>
      <h3>Questions</h3>
      <table class = "table">
        <thead>
          <tr>
            <th colspan="1">ID</th>
            <th colspan="1">Content</th>
          </tr>
        <thead>
        <tbody>
      <%= @surveyquestions.each do |sq| %>
      <tr>
        <td> <%= sq %> </td>
        <td> <%= @questions.find(sq).context %> </td>
      </tr>
      <% end %>
    </tbody>
    <%= link_to "Edit", edit_survey_path(@survey), {:class => "btn btn-primary"}%>
  </table>
      <br>
      <br>
  </div>